version: "2.3"

dependencies: 
  - project: LangBledsoe/spring-petclinic
    dependencies:
      - project: LangBledsoe/joda-time
        mapping:
          dependencies:
            default:
              - source: main
                target: master

default:
  build-command:
    current: mvn clean install -DskipTests=false
    upstream: mvn clean install -DskipTests=false
    downstream: mvn clean install -DskipTests=false