version: "2.1"

dependencies: 
  - project: LangBledsoe/joda-time
    dependencies:
      - project: LangBledsoe/spring-petclinic
        mapping:
          dependencies:
            - source: pom.xml
              target: pom.xml

default:
  build-command:
    current: mvn clean install
    upstream: mvn clean install
    downstream: mvn clean install
  build-command-upstream: mvn clean install
  build-command-downstream: mvn clean install