name: Java CI with Maven - Joda-Time

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set up Nexus Repository
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: maven-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: TESTING - Verify Maven Config
        run: cat ~/.m2/settings.xml

      - name: Publish package to Nexus
        run: mvn clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_USER }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

  trigger-spring-petclinic:
    needs: build  # This ensures spring-petclinic is built ONLY IF joda-time succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Build Chain Execution
        uses: ginxo/github-action-build-chain@v2
        with:
          definition-file: https://raw.githubusercontent.com/LangBledsoe/joda-time/master/.ci/pull-request-config.yaml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
