name: Build Chain Flow - Joda-Time

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-chain:
    concurrency:
      group: build-chain-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    name: Build Chain Flow
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: maven-releases
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Build Chain Execution
        id: build-chain
        uses: kiegroup/github-action-build-chain@v3.5.9
        with:
          definition-file: https://raw.githubusercontent.com/LangBledsoe/joda-time/main/.ci/pull-request-config.yaml
          flow-type: full
        env:
          GITHUB_TOKEN: "${{ secrets.LANGS_TOKEN }}"
          MAVEN_USERNAME: "${{ secrets.NEXUS_USER }}"
          MAVEN_PASSWORD: "${{ secrets.NEXUS_PASSWORD }}"
